# 模型配置
model_size: 'm'  # 可选 'n', 's', 'm', 'l', 'x'
model_path: 'yolo11s-obb.pt'  # OBB模型路径
img_size: 1280
model: /path/to/your/trained/model/weights/best.pt    # 要验证的模型路径（可选）

# 数据集配置
data_yaml: '/path/to/your/dataset/data.yaml'  # OBB数据集yaml文件路径

# 验证参数
batch_size: 16
device: '0'  # 使用 GPU device

# 验证特定参数
conf_threshold: 0.25  # 置信度阈值
iou_threshold: 0.45     # IoU阈值
max_det: 2000           # 每张图像的最大检测数量（所有类别总和）

# 保存选项
save_txt: false         # 保存预测结果为txt文件
save_conf: true        # 保存置信度
save_json: true        # 保存为COCO格式JSON
save_crop: true        # 保存裁剪的预测框

# 可视化选项
plots: true            # 生成混淆矩阵等图表
show: false            # 显示结果（验证时建议设为false）
show_labels: true      # 显示标签
show_conf: true        # 显示置信度

# 输出配置
output_base_dir: '/path/to/output/runs/obb/val' 
